---
abstract: 'limit the applicability of a Moose::Role'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: MooseX::RoleFor
name: MooseX-RoleFor
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Carp: 0
  Moose::Exporter: 0
  Moose::Role: 0
  Moose::Util::TypeConstraints: 0
  Scalar::Util: 0
  namespace::autoclean: 0
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=MooseX-RoleFor
  homepage: https://metacpan.org/release/MooseX-RoleFor
  license: http://dev.perl.org/licenses/
version: 0.001
